spring.application.name=service_cine
#Configuration de la base de datos
spring.datasource.url= jdbc:mysql://localhost:3306/cine
spring.datasource.username=root
spring.datasource.password=
#Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

application.security.jwt.secret-key=EstaEsUnaLlaveSuperSecretaParaMiProyectoDeCine2026DebeSerLarga
application.security.jwt.expiration=86400000